test:
	./xunit-check.sh 01-libica.xml 01-libica-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 02-icedtea-web.xml 02-icedtea-web-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 03-nodejs.xml 03-nodejs-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 04-distro.xml 04-distro-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 05-nginx.xml 05-nginx-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 06-thermostat1.xml 06-thermostat1-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 07-nginx.xml 07-nginx-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 08-thermostat1.xml 08-thermostat1-xunit-golden.xml ../../xunit.xsl
	./xunit-check.sh 09-libpng.xml 09-libpng-xunit-golden.xml ../../xunit.xsl
